In [93]:
import numpy as np
from copy import deepcopy

board = np.zeros([7,7])
# board[0][14] = 1

def print_board(board):
    print('  0   1   2   3   4   5   6 ')
    print(' --- --- --- --- --- --- ---')
    for i in range(7):
        temp = []
        temp.append('|')
        for j in range(7):
            if board[i][j] == 0:
                temp.append(' ')
            elif board[i][j] == 1:
                temp.append('@')
            else:
                temp.append('#')
            temp.append('|')
        temp.append(str(i))
        print(' '.join(temp))
        print(' --- --- --- --- --- --- ---')
#         print(' -----------------------------------------------------------')
        
print_board(board)


free_four = 11
space_four = 10
dead_four = 9
free_three =  8
space_three = 7
dead_space_three = 6
dead_three = 5
free_two = 4
space_two = 3
dead_two = 2
single = 1

  0   1   2   3   4   5   6 
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 0
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 1
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 2
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 3
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 4
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 5
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 6
 --- --- --- --- --- --- ---


In [95]:





def find_winning_block_horiz(board, player, v_map):
    print('#check horizontal')
    for i in range(7):
        for j in range(3):
            count = 0
            self_count = 0
            consecutive_count = 0
            consecutive_count_max = 0
            first_self = -1
            seven_block = np.zeros(7)
            for k in range(5):
                if board[i][j+k] == player:
                    consecutive_count += 1
                    v_map[i][j+k] = single if v_map[i][j+k] < single else v_map[i][j+k]
                    count+=1
                    self_count+=1
                    seven_block[k+1] = 1
#                     print('fs', first_self, 'k', k)
                    if first_self == -1:
                        first_self = k
#                     print('fs', first_self, 'k', k)
                    
                elif board[i][j+k] == 0:
                    consecutive_count_max = consecutive_count if consecutive_count > consecutive_count_max else consecutive_count_max
                    consecutive_count = 0
                    count+=1
                    
            consecutive_count_max = consecutive_count if consecutive_count > consecutive_count_max else consecutive_count_max
            
            if j-1 >= 0:
                if board[i][j-1] != 0 and board[i][j-1] != player:
                    seven_block[0] = -1
            else:
                seven_block[0] = -1
            
            if j+5 <= 6:
                if board[i][j+5] != 0 and board[i][j+5] != player:
                    seven_block[6] = -1
            else:
                seven_block[6] = -1
                    
                    
            if count == 5:
                if self_count == 5:
                    v_map[i][j  ] = np.inf
                    v_map[i][j+1] = np.inf
                    v_map[i][j+2] = np.inf
                    v_map[i][j+3] = np.inf
                    v_map[i][j+4] = np.inf
                elif self_count == 4:
                    if consecutive_count_max == 4:
                        if seven_block[first_self] == 0 and seven_block[first_self+5] == 0:
                            v_map[i][j+first_self  ] = free_four if v_map[i][j+first_self  ] < free_four else v_map[i][j+first_self  ]
                            v_map[i][j+first_self+1] = free_four if v_map[i][j+first_self+1] < free_four else v_map[i][j+first_self+1]
                            v_map[i][j+first_self+2] = free_four if v_map[i][j+first_self+2] < free_four else v_map[i][j+first_self+2]
                            v_map[i][j+first_self+3] = free_four if v_map[i][j+first_self+3] < free_four else v_map[i][j+first_self+3]
                        else:
                            v_map[i][j+first_self  ] = dead_four if v_map[i][j+first_self  ] < dead_four else v_map[i][j+first_self  ]
                            v_map[i][j+first_self+1] = dead_four if v_map[i][j+first_self+1] < dead_four else v_map[i][j+first_self+1]
                            v_map[i][j+first_self+2] = dead_four if v_map[i][j+first_self+2] < dead_four else v_map[i][j+first_self+2]
                            v_map[i][j+first_self+3] = dead_four if v_map[i][j+first_self+3] < dead_four else v_map[i][j+first_self+3]
                    
                    elif consecutive_count_max == 3:
                        if seven_block[2] == 0:
                            if seven_block[6] == 0:
                                v_map[i][j  ] = space_four if v_map[i][j  ] < space_four else v_map[i][j  ]
                                v_map[i][j+1] = space_four if v_map[i][j+1] < space_four else v_map[i][j+1]
                                v_map[i][j+2] = space_four if v_map[i][j+2] < space_four else v_map[i][j+2]
                                v_map[i][j+3] = space_four if v_map[i][j+3] < space_four else v_map[i][j+3]
                                v_map[i][j+4] = space_four if v_map[i][j+4] < space_four else v_map[i][j+4]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i][j+n-1] = 0
                            else:
                                v_map[i][j  ] = dead_four if v_map[i][j  ] < dead_four else v_map[i][j  ]
                                v_map[i][j+1] = dead_four if v_map[i][j+1] < dead_four else v_map[i][j+1]
                                v_map[i][j+2] = dead_four if v_map[i][j+2] < dead_four else v_map[i][j+2]
                                v_map[i][j+3] = dead_four if v_map[i][j+3] < dead_four else v_map[i][j+3]
                                v_map[i][j+4] = dead_four if v_map[i][j+4] < dead_four else v_map[i][j+4]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i][j+n-1] = 0
                        elif seven_block[4] == 0:
                            if seven_block[0] == 0:
                                v_map[i][j  ] = space_four if v_map[i][j  ] < space_four else v_map[i][j  ]
                                v_map[i][j+1] = space_four if v_map[i][j+1] < space_four else v_map[i][j+1]
                                v_map[i][j+2] = space_four if v_map[i][j+2] < space_four else v_map[i][j+2]
                                v_map[i][j+3] = space_four if v_map[i][j+3] < space_four else v_map[i][j+3]
                                v_map[i][j+4] = space_four if v_map[i][j+4] < space_four else v_map[i][j+4]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i][j+n-1] = 0
                            else:
                                v_map[i][j  ] = dead_four if v_map[i][j  ] < dead_four else v_map[i][j  ]
                                v_map[i][j+1] = dead_four if v_map[i][j+1] < dead_four else v_map[i][j+1]
                                v_map[i][j+2] = dead_four if v_map[i][j+2] < dead_four else v_map[i][j+2]
                                v_map[i][j+3] = dead_four if v_map[i][j+3] < dead_four else v_map[i][j+3]
                                v_map[i][j+4] = dead_four if v_map[i][j+4] < dead_four else v_map[i][j+4]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i][j+n-1] = 0
                    else:
                        v_map[i][j  ] = dead_four if v_map[i][j  ] < dead_four else v_map[i][j  ]
                        v_map[i][j+1] = dead_four if v_map[i][j+1] < dead_four else v_map[i][j+1]
                        v_map[i][j+2] = dead_four if v_map[i][j+2] < dead_four else v_map[i][j+2]
                        v_map[i][j+3] = dead_four if v_map[i][j+3] < dead_four else v_map[i][j+3]
                        v_map[i][j+4] = dead_four if v_map[i][j+4] < dead_four else v_map[i][j+4]
                        for n in range(1,6):
                            if seven_block[n] == 0:
                                v_map[i][j+n-1] = 0
                                
                elif self_count == 3:
                    if consecutive_count_max == 3:
                        if seven_block[first_self] == 0 and seven_block[first_self+4] == 0:
                            v_map[i][j+first_self  ] = free_three if v_map[i][j+first_self  ] < free_three else v_map[i][j+first_self  ]
                            v_map[i][j+first_self+1] = free_three if v_map[i][j+first_self+1] < free_three else v_map[i][j+first_self+1]
                            v_map[i][j+first_self+2] = free_three if v_map[i][j+first_self+2] < free_three else v_map[i][j+first_self+2]
                        else:
                            v_map[i][j+first_self  ] = dead_three if v_map[i][j+first_self  ] < dead_three else v_map[i][j+first_self  ]
                            v_map[i][j+first_self+1] = dead_three if v_map[i][j+first_self+1] < dead_three else v_map[i][j+first_self+1]
                            v_map[i][j+first_self+2] = dead_three if v_map[i][j+first_self+2] < dead_three else v_map[i][j+first_self+2]
                            
                    elif consecutive_count_max == 2:
                        if seven_block[1] == 1 and seven_block[5] == 1:
                            if seven_block[2] == 0 and seven_block[3] == 0:
                                if seven_block[6] == 0:
                                    v_map[i][j  ] = dead_space_three if v_map[i][j  ] < dead_space_three else v_map[i][j  ]
                                    v_map[i][j+1] = dead_space_three if v_map[i][j+1] < dead_space_three else v_map[i][j+1]
                                    v_map[i][j+2] = dead_space_three if v_map[i][j+2] < dead_space_three else v_map[i][j+2]
                                    v_map[i][j+3] = dead_space_three if v_map[i][j+3] < dead_space_three else v_map[i][j+3]
                                    v_map[i][j+4] = dead_space_three if v_map[i][j+4] < dead_space_three else v_map[i][j+4]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i][j+n-1] = 0
                                else:
                                    v_map[i][j  ] = dead_three if v_map[i][j  ] < dead_three else v_map[i][j  ]
                                    v_map[i][j+1] = dead_three if v_map[i][j+1] < dead_three else v_map[i][j+1]
                                    v_map[i][j+2] = dead_three if v_map[i][j+2] < dead_three else v_map[i][j+2]
                                    v_map[i][j+3] = dead_three if v_map[i][j+3] < dead_three else v_map[i][j+3]
                                    v_map[i][j+4] = dead_three if v_map[i][j+4] < dead_three else v_map[i][j+4]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i][j+n-1] = 0
                            if seven_block[3] == 0 and seven_block[4] == 0:
                                if seven_block[0] == 0:
                                    v_map[i][j  ] = dead_space_three if v_map[i][j  ] < dead_space_three else v_map[i][j  ]
                                    v_map[i][j+1] = dead_space_three if v_map[i][j+1] < dead_space_three else v_map[i][j+1]
                                    v_map[i][j+2] = dead_space_three if v_map[i][j+2] < dead_space_three else v_map[i][j+2]
                                    v_map[i][j+3] = dead_space_three if v_map[i][j+3] < dead_space_three else v_map[i][j+3]
                                    v_map[i][j+4] = dead_space_three if v_map[i][j+4] < dead_space_three else v_map[i][j+4]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i][j+n-1] = 0
                                else:
                                    v_map[i][j  ] = dead_three if v_map[i][j  ] < dead_three else v_map[i][j  ]
                                    v_map[i][j+1] = dead_three if v_map[i][j+1] < dead_three else v_map[i][j+1]
                                    v_map[i][j+2] = dead_three if v_map[i][j+2] < dead_three else v_map[i][j+2]
                                    v_map[i][j+3] = dead_three if v_map[i][j+3] < dead_three else v_map[i][j+3]
                                    v_map[i][j+4] = dead_three if v_map[i][j+4] < dead_three else v_map[i][j+4]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i][j+n-1] = 0 
                                    
                        elif seven_block[first_self] == 0 and seven_block[first_self+5] == 0:
                            v_map[i][j+first_self  ] = space_three if v_map[i][j+first_self  ] < space_three else v_map[i][j+first_self  ]
                            v_map[i][j+first_self+1] = space_three if v_map[i][j+first_self+1] < space_three else v_map[i][j+first_self+1]
                            v_map[i][j+first_self+2] = space_three if v_map[i][j+first_self+2] < space_three else v_map[i][j+first_self+2]
                            v_map[i][j+first_self+3] = space_three if v_map[i][j+first_self+3] < space_three else v_map[i][j+first_self+3]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i][j+n-1] = 0
                                    
                        elif seven_block[first_self] == 0 and seven_block[first_self+3] == 0:
                            v_map[i][j+first_self  ] = dead_space_three if v_map[i][j+first_self  ] < dead_space_three else v_map[i][j+first_self  ]
                            v_map[i][j+first_self+1] = dead_space_three if v_map[i][j+first_self+1] < dead_space_three else v_map[i][j+first_self+1]
                            v_map[i][j+first_self+2] = dead_space_three if v_map[i][j+first_self+2] < dead_space_three else v_map[i][j+first_self+2]
                            v_map[i][j+first_self+3] = dead_space_three if v_map[i][j+first_self+3] < dead_space_three else v_map[i][j+first_self+3]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i][j+n-1] = 0
                                    
                        elif seven_block[first_self+5] == 0 and seven_block[first_self+2] == 0:
                            v_map[i][j+first_self  ] = dead_space_three if v_map[i][j+first_self  ] < dead_space_three else v_map[i][j+first_self  ]
                            v_map[i][j+first_self+1] = dead_space_three if v_map[i][j+first_self+1] < dead_space_three else v_map[i][j+first_self+1]
                            v_map[i][j+first_self+2] = dead_space_three if v_map[i][j+first_self+2] < dead_space_three else v_map[i][j+first_self+2]
                            v_map[i][j+first_self+3] = dead_space_three if v_map[i][j+first_self+3] < dead_space_three else v_map[i][j+first_self+3]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i][j+n-1] = 0
                        
                        else:
                            v_map[i][j+first_self  ] = dead_three if v_map[i][j+first_self  ] < dead_three else v_map[i][j+first_self  ]
                            v_map[i][j+first_self+1] = dead_three if v_map[i][j+first_self+1] < dead_three else v_map[i][j+first_self+1]
                            v_map[i][j+first_self+2] = dead_three if v_map[i][j+first_self+2] < dead_three else v_map[i][j+first_self+2]
                            v_map[i][j+first_self+3] = dead_three if v_map[i][j+first_self+3] < dead_three else v_map[i][j+first_self+3]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i][j+n-1] = 0
                                    
                    elif consecutive_count_max == 1:
                        if seven_block[0] == 0 or seven_block[6] == 0:
                            v_map[i][j  ] = dead_space_three if v_map[i][j  ] < dead_space_three else v_map[i][j  ]
                            v_map[i][j+1] = dead_space_three if v_map[i][j+1] < dead_space_three else v_map[i][j+1]
                            v_map[i][j+2] = dead_space_three if v_map[i][j+2] < dead_space_three else v_map[i][j+2]
                            v_map[i][j+3] = dead_space_three if v_map[i][j+3] < dead_space_three else v_map[i][j+3]
                            v_map[i][j+4] = dead_space_three if v_map[i][j+4] < dead_space_three else v_map[i][j+4]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i][j+n-1] = 0  
                        else:
                            v_map[i][j  ] = dead_three if v_map[i][j  ] < dead_three else v_map[i][j  ]
                            v_map[i][j+1] = dead_three if v_map[i][j+1] < dead_three else v_map[i][j+1]
                            v_map[i][j+2] = dead_three if v_map[i][j+2] < dead_three else v_map[i][j+2]
                            v_map[i][j+3] = dead_three if v_map[i][j+3] < dead_three else v_map[i][j+3]
                            v_map[i][j+4] = dead_three if v_map[i][j+4] < dead_three else v_map[i][j+4]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i][j+n-1] = 0 
                            
                elif self_count == 2:
                    if consecutive_count_max == 2:
                        if seven_block[first_self] == 0 and seven_block[first_self+3] == 0:
                            v_map[i][j+first_self  ] = free_two if v_map[i][j+first_self  ] < free_two else v_map[i][j+first_self  ]
                            v_map[i][j+first_self+1] = free_two if v_map[i][j+first_self+1] < free_two else v_map[i][j+first_self+1]
                        else:
                            v_map[i][j+first_self  ] = dead_two if v_map[i][j+first_self  ] < dead_two else v_map[i][j+first_self  ]
                            v_map[i][j+first_self+1] = dead_two if v_map[i][j+first_self+1] < dead_two else v_map[i][j+first_self+1]
                            
                    else:
                        if seven_block[first_self] == 0 and seven_block[first_self+4] == 0:
                            v_map[i][j+first_self  ] = space_two if v_map[i][j+first_self  ] < space_two else v_map[i][j+first_self  ]
                            v_map[i][j+first_self+1] = space_two if v_map[i][j+first_self+1] < space_two else v_map[i][j+first_self+1]
                            v_map[i][j+first_self+2] = space_two if v_map[i][j+first_self+2] < space_two else v_map[i][j+first_self+2]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i][j+n-1] = 0 
                        else:
                            v_map[i][j+first_self  ] = dead_two if v_map[i][j+first_self  ] < dead_two else v_map[i][j+first_self  ]
                            v_map[i][j+first_self+1] = dead_two if v_map[i][j+first_self+1] < dead_two else v_map[i][j+first_self+1]
                            v_map[i][j+first_self+2] = dead_two if v_map[i][j+first_self+2] < dead_two else v_map[i][j+first_self+2]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i][j+n-1] = 0 


In [96]:
#test horiz
v_map = np.zeros([7,7])
board = np.zeros([7,7])
board[1][0] = 1
board[1][1] = 1
board[1][2] = 2
board[1][3] = 1
board[1][4] = 1
board[1][5] = 1
board[1][6] = 1

find_winning_block_horiz(board, 1, v_map)

print_board(board)
print(v_map)


#check horizontal
  0   1   2   3   4   5   6 
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 0
 --- --- --- --- --- --- ---
| @ | @ | # | @ | @ | @ | @ | 1
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 2
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 3
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 4
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 5
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 6
 --- --- --- --- --- --- ---
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [97]:

def find_winning_block_vertical(board, player, v_map):
    print('#check horizontal')
    for i in range(3):
        for j in range(7):
            count = 0
            self_count = 0
            consecutive_count = 0
            consecutive_count_max = 0
            first_self = -1
            seven_block = np.zeros(7)
            for k in range(5):
                if board[i+k][j] == player:
                    consecutive_count += 1
                    v_map[i+k][j] = single if v_map[i+k][j] < single else v_map[i+k][j]
                    count+=1
                    self_count+=1
                    seven_block[k+1] = 1
#                     print('fs', first_self, 'k', k)
                    if first_self == -1:
                        first_self = k
#                     print('fs', first_self, 'k', k)
                    
                elif board[i+k][j] == 0:
                    consecutive_count_max = consecutive_count if consecutive_count > consecutive_count_max else consecutive_count_max
                    consecutive_count = 0
                    count+=1
                    
            consecutive_count_max = consecutive_count if consecutive_count > consecutive_count_max else consecutive_count_max
            
            if i-1 >= 0:
                if board[i-1][j] != 0 and board[i-1][j] != player:
                    seven_block[0] = -1
            else:
                seven_block[0] = -1
            
            if i+5 <= 6:
                if board[i+5][j] != 0 and board[i+5][j] != player:
                    seven_block[6] = -1
            else:
                seven_block[6] = -1
                    
                    
            if count == 5:
                if self_count == 5:
                    v_map[i  ][j] = np.inf
                    v_map[i+1][j] = np.inf
                    v_map[i+2][j] = np.inf
                    v_map[i+3][j] = np.inf
                    v_map[i+4][j] = np.inf
                elif self_count == 4:
                    if consecutive_count_max == 4:
                        if seven_block[first_self] == 0 and seven_block[first_self+5] == 0:
                            v_map[i+first_self  ][j] = free_four if v_map[i+first_self  ][j] < free_four else v_map[i+first_self  ][j]
                            v_map[i+first_self+1][j] = free_four if v_map[i+first_self+1][j] < free_four else v_map[i+first_self+1][j]
                            v_map[i+first_self+2][j] = free_four if v_map[i+first_self+2][j] < free_four else v_map[i+first_self+2][j]
                            v_map[i+first_self+3][j] = free_four if v_map[i+first_self+3][j] < free_four else v_map[i+first_self+3][j]
                        else:
                            v_map[i+first_self  ][j] = dead_four if v_map[i+first_self  ][j] < dead_four else v_map[i+first_self  ][j]
                            v_map[i+first_self+1][j] = dead_four if v_map[i+first_self+1][j] < dead_four else v_map[i+first_self+1][j]
                            v_map[i+first_self+2][j] = dead_four if v_map[i+first_self+2][j] < dead_four else v_map[i+first_self+2][j]
                            v_map[i+first_self+3][j] = dead_four if v_map[i+first_self+3][j] < dead_four else v_map[i+first_self+3][j]
                    
                    elif consecutive_count_max == 3:
                        if seven_block[2] == 0:
                            if seven_block[6] == 0:
                                v_map[i  ][j] = space_four if v_map[i  ][j] < space_four else v_map[i  ][j]
                                v_map[i+1][j] = space_four if v_map[i+1][j] < space_four else v_map[i+1][j]
                                v_map[i+2][j] = space_four if v_map[i+2][j] < space_four else v_map[i+2][j]
                                v_map[i+3][j] = space_four if v_map[i+3][j] < space_four else v_map[i+3][j]
                                v_map[i+4][j] = space_four if v_map[i+4][j] < space_four else v_map[i+4][j]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i+n-1][j] = 0
                            else:
                                v_map[i  ][j] = dead_four if v_map[i  ][j] < dead_four else v_map[i  ][j]
                                v_map[i+1][j] = dead_four if v_map[i+1][j] < dead_four else v_map[i+1][j]
                                v_map[i+2][j] = dead_four if v_map[i+2][j] < dead_four else v_map[i+2][j]
                                v_map[i+3][j] = dead_four if v_map[i+3][j] < dead_four else v_map[i+3][j]
                                v_map[i+4][j] = dead_four if v_map[i+4][j] < dead_four else v_map[i+4][j]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i+n-1][j] = 0
                        elif seven_block[4] == 0:
                            if seven_block[0] == 0:
                                v_map[i  ][j] = space_four if v_map[i  ][j] < space_four else v_map[i  ][j]
                                v_map[i+1][j] = space_four if v_map[i+1][j] < space_four else v_map[i+1][j]
                                v_map[i+2][j] = space_four if v_map[i+2][j] < space_four else v_map[i+2][j]
                                v_map[i+3][j] = space_four if v_map[i+3][j] < space_four else v_map[i+3][j]
                                v_map[i+4][j] = space_four if v_map[i+4][j] < space_four else v_map[i+4][j]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i+n-1][j] = 0
                            else:
                                v_map[i  ][j] = dead_four if v_map[i  ][j] < dead_four else v_map[i  ][j]
                                v_map[i+1][j] = dead_four if v_map[i+1][j] < dead_four else v_map[i+1][j]
                                v_map[i+2][j] = dead_four if v_map[i+2][j] < dead_four else v_map[i+2][j]
                                v_map[i+3][j] = dead_four if v_map[i+3][j] < dead_four else v_map[i+3][j]
                                v_map[i+4][j] = dead_four if v_map[i+4][j] < dead_four else v_map[i+4][j]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i+n-1][j] = 0
                    else:
                        v_map[i  ][j] = dead_four if v_map[i  ][j] < dead_four else v_map[i  ][j]
                        v_map[i+1][j] = dead_four if v_map[i+1][j] < dead_four else v_map[i+1][j]
                        v_map[i+2][j] = dead_four if v_map[i+2][j] < dead_four else v_map[i+2][j]
                        v_map[i+3][j] = dead_four if v_map[i+3][j] < dead_four else v_map[i+3][j]
                        v_map[i+4][j] = dead_four if v_map[i+4][j] < dead_four else v_map[i+4][j]
                        for n in range(1,6):
                            if seven_block[n] == 0:
                                v_map[i+n-1][j] = 0
                                
                elif self_count == 3:
                    if consecutive_count_max == 3:
                        if seven_block[first_self] == 0 and seven_block[first_self+4] == 0:
                            v_map[i+first_self  ][j] = free_three if v_map[i+first_self  ][j] < free_three else v_map[i+first_self  ][j]
                            v_map[i+first_self+1][j] = free_three if v_map[i+first_self+1][j] < free_three else v_map[i+first_self+1][j]
                            v_map[i+first_self+2][j] = free_three if v_map[i+first_self+2][j] < free_three else v_map[i+first_self+2][j]
                        else:
                            v_map[i+first_self  ][j] = dead_three if v_map[i+first_self  ][j] < dead_three else v_map[i+first_self  ][j]
                            v_map[i+first_self+1][j] = dead_three if v_map[i+first_self+1][j] < dead_three else v_map[i+first_self+1][j]
                            v_map[i+first_self+2][j] = dead_three if v_map[i+first_self+2][j] < dead_three else v_map[i+first_self+2][j]
                            
                    elif consecutive_count_max == 2:
                        if seven_block[1] == 1 and seven_block[5] == 1:
                            if seven_block[2] == 0 and seven_block[3] == 0:
                                if seven_block[6] == 0:
                                    v_map[i  ][j] = dead_space_three if v_map[i  ][j] < dead_space_three else v_map[i  ][j]
                                    v_map[i+1][j] = dead_space_three if v_map[i+1][j] < dead_space_three else v_map[i+1][j]
                                    v_map[i+2][j] = dead_space_three if v_map[i+2][j] < dead_space_three else v_map[i+2][j]
                                    v_map[i+3][j] = dead_space_three if v_map[i+3][j] < dead_space_three else v_map[i+3][j]
                                    v_map[i+4][j] = dead_space_three if v_map[i+4][j] < dead_space_three else v_map[i+4][j]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i+n-1][j] = 0
                                else:
                                    v_map[i  ][j] = dead_three if v_map[i  ][j] < dead_three else v_map[i  ][j]
                                    v_map[i+1][j] = dead_three if v_map[i+1][j] < dead_three else v_map[i+1][j]
                                    v_map[i+2][j] = dead_three if v_map[i+2][j] < dead_three else v_map[i+2][j]
                                    v_map[i+3][j] = dead_three if v_map[i+3][j] < dead_three else v_map[i+3][j]
                                    v_map[i+4][j] = dead_three if v_map[i+4][j] < dead_three else v_map[i+4][j]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i+n-1][j] = 0
                            if seven_block[3] == 0 and seven_block[4] == 0:
                                if seven_block[0] == 0:
                                    v_map[i  ][j] = dead_space_three if v_map[i  ][j] < dead_space_three else v_map[i  ][j]
                                    v_map[i+1][j] = dead_space_three if v_map[i+1][j] < dead_space_three else v_map[i+1][j]
                                    v_map[i+2][j] = dead_space_three if v_map[i+2][j] < dead_space_three else v_map[i+2][j]
                                    v_map[i+3][j] = dead_space_three if v_map[i+3][j] < dead_space_three else v_map[i+3][j]
                                    v_map[i+4][j] = dead_space_three if v_map[i+4][j] < dead_space_three else v_map[i+4][j]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i+n-1][j] = 0
                                else:
                                    v_map[i  ][j] = dead_three if v_map[i  ][j] < dead_three else v_map[i  ][j]
                                    v_map[i+1][j] = dead_three if v_map[i+1][j] < dead_three else v_map[i+1][j]
                                    v_map[i+2][j] = dead_three if v_map[i+2][j] < dead_three else v_map[i+2][j]
                                    v_map[i+3][j] = dead_three if v_map[i+3][j] < dead_three else v_map[i+3][j]
                                    v_map[i+4][j] = dead_three if v_map[i+4][j] < dead_three else v_map[i+4][j]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i+n-1][j] = 0
                                    
                        elif seven_block[first_self] == 0 and seven_block[first_self+5] == 0:
                            v_map[i+first_self  ][j] = space_three if v_map[i+first_self  ][j] < space_three else v_map[i+first_self  ][j]
                            v_map[i+first_self+1][j] = space_three if v_map[i+first_self+1][j] < space_three else v_map[i+first_self+1][j]
                            v_map[i+first_self+2][j] = space_three if v_map[i+first_self+2][j] < space_three else v_map[i+first_self+2][j]
                            v_map[i+first_self+3][j] = space_three if v_map[i+first_self+3][j] < space_three else v_map[i+first_self+3][j]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j] = 0
                                    
                        elif seven_block[first_self] == 0 and seven_block[first_self+3] == 0:
                            v_map[i+first_self  ][j] = dead_space_three if v_map[i+first_self  ][j] < dead_space_three else v_map[i+first_self  ][j]
                            v_map[i+first_self+1][j] = dead_space_three if v_map[i+first_self+1][j] < dead_space_three else v_map[i+first_self+1][j]
                            v_map[i+first_self+2][j] = dead_space_three if v_map[i+first_self+2][j] < dead_space_three else v_map[i+first_self+2][j]
                            v_map[i+first_self+3][j] = dead_space_three if v_map[i+first_self+3][j] < dead_space_three else v_map[i+first_self+3][j]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j] = 0
                                    
                        elif seven_block[first_self+5] == 0 and seven_block[first_self+2] == 0:
                            v_map[i+first_self  ][j] = dead_space_three if v_map[i+first_self  ][j] < dead_space_three else v_map[i+first_self  ][j]
                            v_map[i+first_self+1][j] = dead_space_three if v_map[i+first_self+1][j] < dead_space_three else v_map[i+first_self+1][j]
                            v_map[i+first_self+2][j] = dead_space_three if v_map[i+first_self+2][j] < dead_space_three else v_map[i+first_self+2][j]
                            v_map[i+first_self+3][j] = dead_space_three if v_map[i+first_self+3][j] < dead_space_three else v_map[i+first_self+3][j]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j] = 0
                        
                        else:
                            v_map[i+first_self  ][j] = dead_three if v_map[i+first_self  ][j] < dead_three else v_map[i+first_self  ][j]
                            v_map[i+first_self+1][j] = dead_three if v_map[i+first_self+1][j] < dead_three else v_map[i+first_self+1][j]
                            v_map[i+first_self+2][j] = dead_three if v_map[i+first_self+2][j] < dead_three else v_map[i+first_self+2][j]
                            v_map[i+first_self+3][j] = dead_three if v_map[i+first_self+3][j] < dead_three else v_map[i+first_self+3][j]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j] = 0
                                    
                    elif consecutive_count_max == 1:
                        if seven_block[0] == 0 or seven_block[6] == 0:
                            v_map[i  ][j] = dead_space_three if v_map[i  ][j] < dead_space_three else v_map[i  ][j]
                            v_map[i+1][j] = dead_space_three if v_map[i+1][j] < dead_space_three else v_map[i+1][j]
                            v_map[i+2][j] = dead_space_three if v_map[i+2][j] < dead_space_three else v_map[i+2][j]
                            v_map[i+3][j] = dead_space_three if v_map[i+3][j] < dead_space_three else v_map[i+3][j]
                            v_map[i+4][j] = dead_space_three if v_map[i+4][j] < dead_space_three else v_map[i+4][j]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j] = 0
                        else:
                            v_map[i  ][j] = dead_three if v_map[i  ][j] < dead_three else v_map[i  ][j]
                            v_map[i+1][j] = dead_three if v_map[i+1][j] < dead_three else v_map[i+1][j]
                            v_map[i+2][j] = dead_three if v_map[i+2][j] < dead_three else v_map[i+2][j]
                            v_map[i+3][j] = dead_three if v_map[i+3][j] < dead_three else v_map[i+3][j]
                            v_map[i+4][j] = dead_three if v_map[i+4][j] < dead_three else v_map[i+4][j]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j] = 0
                            
                elif self_count == 2:
                    if consecutive_count_max == 2:
                        if seven_block[first_self] == 0 and seven_block[first_self+3] == 0:
                            v_map[i+first_self  ][j] = free_two if v_map[i+first_self  ][j] < free_two else v_map[i+first_self  ][j]
                            v_map[i+first_self+1][j] = free_two if v_map[i+first_self+1][j] < free_two else v_map[i+first_self+1][j]
                        else:
                            v_map[i+first_self  ][j] = dead_two if v_map[i+first_self  ][j] < dead_two else v_map[i+first_self  ][j]
                            v_map[i+first_self+1][j] = dead_two if v_map[i+first_self+1][j] < dead_two else v_map[i+first_self+1][j]
                            
                    else:
                        if seven_block[first_self] == 0 and seven_block[first_self+4] == 0:
                            v_map[i+first_self  ][j] = space_two if v_map[i+first_self  ][j] < space_two else v_map[i+first_self  ][j]
                            v_map[i+first_self+1][j] = space_two if v_map[i+first_self+1][j] < space_two else v_map[i+first_self+1][j]
                            v_map[i+first_self+2][j] = space_two if v_map[i+first_self+2][j] < space_two else v_map[i+first_self+2][j]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j] = 0
                        else:
                            v_map[i+first_self  ][j] = dead_two if v_map[i+first_self  ][j] < dead_two else v_map[i+first_self  ][j]
                            v_map[i+first_self+1][j] = dead_two if v_map[i+first_self+1][j] < dead_two else v_map[i+first_self+1][j]
                            v_map[i+first_self+2][j] = dead_two if v_map[i+first_self+2][j] < dead_two else v_map[i+first_self+2][j]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j] = 0

In [98]:
#test vertical
v_map = np.zeros([7,7])
board = np.zeros([7,7])
board[0][1] = 0
board[1][1] = 1
board[2][1] = 0
board[3][1] = 1
board[4][1] = 0
board[5][1] = 0
board[6][1] = 0

find_winning_block_vertical(board, 1, v_map)

print_board(board)
print(v_map)


#check horizontal
  0   1   2   3   4   5   6 
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 0
 --- --- --- --- --- --- ---
|   | @ |   |   |   |   |   | 1
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 2
 --- --- --- --- --- --- ---
|   | @ |   |   |   |   |   | 3
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 4
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 5
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 6
 --- --- --- --- --- --- ---
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  3.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  3.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [101]:

def find_winning_block_rd(board, player, v_map):
    print('#check right donw')
    for i in range(3):
        for j in range(3):
            count = 0
            self_count = 0
            consecutive_count = 0
            consecutive_count_max = 0
            first_self = -1
            seven_block = np.zeros(7)
            for k in range(5):
                if board[i+k][j+k] == player:
                    consecutive_count += 1
                    v_map[i+k][j+k] = single if v_map[i+k][j+k] < single else v_map[i+k][j+k]
                    count+=1
                    self_count+=1
                    seven_block[k+1] = 1
#                     print('fs', first_self, 'k', k)
                    if first_self == -1:
                        first_self = k
#                     print('fs', first_self, 'k', k)
                    
                elif board[i+k][j+k] == 0:
                    consecutive_count_max = consecutive_count if consecutive_count > consecutive_count_max else consecutive_count_max
                    consecutive_count = 0
                    count+=1
                    
            consecutive_count_max = consecutive_count if consecutive_count > consecutive_count_max else consecutive_count_max
            
            if i-1 >= 0 and j-1>=0:
                if board[i-1][j-1] != 0 and board[i-1][j-1] != player:
                    seven_block[0] = -1
            else:
                seven_block[0] = -1
            
            if i+5 <= 6 and j+5<=6:
                if board[i+5][j+5] != 0 and board[i+5][j+5] != player:
                    seven_block[6] = -1
            else:
                seven_block[6] = -1
                    
#             print(seven_block)
            if count == 5:
                if self_count == 5:
                    v_map[i  ][j  ] = np.inf
                    v_map[i+1][j+1] = np.inf
                    v_map[i+2][j+2] = np.inf
                    v_map[i+3][j+3] = np.inf
                    v_map[i+4][j+4] = np.inf
                elif self_count == 4:
                    if consecutive_count_max == 4:
                        if seven_block[first_self] == 0 and seven_block[first_self+5] == 0:
                            v_map[i+first_self  ][j+first_self  ] = free_four if v_map[i+first_self  ][j+first_self  ] < free_four else v_map[i+first_self  ][j+first_self  ]
                            v_map[i+first_self+1][j+first_self+1] = free_four if v_map[i+first_self+1][j+first_self+1] < free_four else v_map[i+first_self+1][j+first_self+1]
                            v_map[i+first_self+2][j+first_self+2] = free_four if v_map[i+first_self+2][j+first_self+2] < free_four else v_map[i+first_self+2][j+first_self+2]
                            v_map[i+first_self+3][j+first_self+3] = free_four if v_map[i+first_self+3][j+first_self+3] < free_four else v_map[i+first_self+3][j+first_self+3]
                        else:
                            v_map[i+first_self  ][j+first_self  ] = dead_four if v_map[i+first_self  ][j+first_self  ] < dead_four else v_map[i+first_self  ][j+first_self  ]
                            v_map[i+first_self+1][j+first_self+1] = dead_four if v_map[i+first_self+1][j+first_self+1] < dead_four else v_map[i+first_self+1][j+first_self+1]
                            v_map[i+first_self+2][j+first_self+2] = dead_four if v_map[i+first_self+2][j+first_self+2] < dead_four else v_map[i+first_self+2][j+first_self+2]
                            v_map[i+first_self+3][j+first_self+3] = dead_four if v_map[i+first_self+3][j+first_self+3] < dead_four else v_map[i+first_self+3][j+first_self+3]
                    
                    elif consecutive_count_max == 3:
                        if seven_block[2] == 0:
                            if seven_block[6] == 0:
                                v_map[i  ][j  ] = space_four if v_map[i  ][j  ] < space_four else v_map[i  ][j  ]
                                v_map[i+1][j+1] = space_four if v_map[i+1][j+1] < space_four else v_map[i+1][j+1]
                                v_map[i+2][j+2] = space_four if v_map[i+2][j+2] < space_four else v_map[i+2][j+2]
                                v_map[i+3][j+3] = space_four if v_map[i+3][j+3] < space_four else v_map[i+3][j+3]
                                v_map[i+4][j+4] = space_four if v_map[i+4][j+4] < space_four else v_map[i+4][j+4]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i+n-1][j+n-1] = 0
                            else:
                                v_map[i  ][j  ] = dead_four if v_map[i  ][j  ] < dead_four else v_map[i  ][j  ]
                                v_map[i+1][j+1] = dead_four if v_map[i+1][j+1] < dead_four else v_map[i+1][j+1]
                                v_map[i+2][j+2] = dead_four if v_map[i+2][j+2] < dead_four else v_map[i+2][j+2]
                                v_map[i+3][j+3] = dead_four if v_map[i+3][j+3] < dead_four else v_map[i+3][j+3]
                                v_map[i+4][j+4] = dead_four if v_map[i+4][j+4] < dead_four else v_map[i+4][j+4]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i+n-1][j+n-1] = 0
                        elif seven_block[4] == 0:
                            if seven_block[0] == 0:
                                v_map[i  ][j  ] = space_four if v_map[i  ][j  ] < space_four else v_map[i  ][j  ]
                                v_map[i+1][j+1] = space_four if v_map[i+1][j+1] < space_four else v_map[i+1][j+1]
                                v_map[i+2][j+2] = space_four if v_map[i+2][j+2] < space_four else v_map[i+2][j+2]
                                v_map[i+3][j+3] = space_four if v_map[i+3][j+3] < space_four else v_map[i+3][j+3]
                                v_map[i+4][j+4] = space_four if v_map[i+4][j+4] < space_four else v_map[i+4][j+4]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i+n-1][j+n-1] = 0
                            else:
                                v_map[i  ][j  ] = dead_four if v_map[i  ][j  ] < dead_four else v_map[i  ][j  ]
                                v_map[i+1][j+1] = dead_four if v_map[i+1][j+1] < dead_four else v_map[i+1][j+1]
                                v_map[i+2][j+2] = dead_four if v_map[i+2][j+2] < dead_four else v_map[i+2][j+2]
                                v_map[i+3][j+3] = dead_four if v_map[i+3][j+3] < dead_four else v_map[i+3][j+3]
                                v_map[i+4][j+4] = dead_four if v_map[i+4][j+4] < dead_four else v_map[i+4][j+4]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i+n-1][j+n-1] = 0
                    else:
                        v_map[i  ][j  ] = dead_four if v_map[i  ][j  ] < dead_four else v_map[i  ][j  ]
                        v_map[i+1][j+1] = dead_four if v_map[i+1][j+1] < dead_four else v_map[i+1][j+1]
                        v_map[i+2][j+2] = dead_four if v_map[i+2][j+2] < dead_four else v_map[i+2][j+2]
                        v_map[i+3][j+3] = dead_four if v_map[i+3][j+3] < dead_four else v_map[i+3][j+3]
                        v_map[i+4][j+4] = dead_four if v_map[i+4][j+4] < dead_four else v_map[i+4][j+4]
                        for n in range(1,6):
                            if seven_block[n] == 0:
                                v_map[i+n-1][j+n-1] = 0
                                
                elif self_count == 3:
                    if consecutive_count_max == 3:
                        if seven_block[first_self] == 0 and seven_block[first_self+4] == 0:
                            v_map[i+first_self  ][j+first_self  ] = free_three if v_map[i+first_self  ][j+first_self  ] < free_three else v_map[i+first_self  ][j+first_self  ]
                            v_map[i+first_self+1][j+first_self+1] = free_three if v_map[i+first_self+1][j+first_self+1] < free_three else v_map[i+first_self+1][j+first_self+1]
                            v_map[i+first_self+2][j+first_self+2] = free_three if v_map[i+first_self+2][j+first_self+2] < free_three else v_map[i+first_self+2][j+first_self+2]
#                             v_map[i+first_self+3][j+first_self+3] = free_three if v_map[i+first_self+3][j+first_self+3] < free_three else v_map[i+first_self+3][j+first_self+3]
                        else:
                            v_map[i+first_self  ][j+first_self  ] = dead_three if v_map[i+first_self  ][j+first_self  ] < dead_three else v_map[i+first_self  ][j+first_self  ]
                            v_map[i+first_self+1][j+first_self+1] = dead_three if v_map[i+first_self+1][j+first_self+1] < dead_three else v_map[i+first_self+1][j+first_self+1]
                            v_map[i+first_self+2][j+first_self+2] = dead_three if v_map[i+first_self+2][j+first_self+2] < dead_three else v_map[i+first_self+2][j+first_self+2]
#                             v_map[i+first_self+3][j+first_self+3] = free_three if v_map[i+first_self+3][j+first_self+3] < free_three else v_map[i+first_self+3][j+first_self+3]
                            
                    elif consecutive_count_max == 2:
                        if seven_block[1] == 1 and seven_block[5] == 1:
                            if seven_block[2] == 0 and seven_block[3] == 0:
                                if seven_block[6] == 0:
                                    v_map[i  ][j  ] = dead_space_three if v_map[i  ][j  ] < dead_space_three else v_map[i  ][j  ]
                                    v_map[i+1][j+1] = dead_space_three if v_map[i+1][j+1] < dead_space_three else v_map[i+1][j+1]
                                    v_map[i+2][j+2] = dead_space_three if v_map[i+2][j+2] < dead_space_three else v_map[i+2][j+2]
                                    v_map[i+3][j+3] = dead_space_three if v_map[i+3][j+3] < dead_space_three else v_map[i+3][j+3]
                                    v_map[i+4][j+4] = dead_space_three if v_map[i+4][j+4] < dead_space_three else v_map[i+4][j+4]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i+n-1][j+n-1] = 0
                                else:
                                    v_map[i  ][j  ] = dead_three if v_map[i  ][j  ] < dead_three else v_map[i  ][j  ]
                                    v_map[i+1][j+1] = dead_three if v_map[i+1][j+1] < dead_three else v_map[i+1][j+1]
                                    v_map[i+2][j+2] = dead_three if v_map[i+2][j+2] < dead_three else v_map[i+2][j+2]
                                    v_map[i+3][j+3] = dead_three if v_map[i+3][j+3] < dead_three else v_map[i+3][j+3]
                                    v_map[i+4][j+4] = dead_three if v_map[i+4][j+4] < dead_three else v_map[i+4][j+4]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i+n-1][j+n-1] = 0
                            if seven_block[3] == 0 and seven_block[4] == 0:
                                if seven_block[0] == 0:
                                    v_map[i  ][j  ] = dead_space_three if v_map[i  ][j  ] < dead_space_three else v_map[i  ][j  ]
                                    v_map[i+1][j+1] = dead_space_three if v_map[i+1][j+1] < dead_space_three else v_map[i+1][j+1]
                                    v_map[i+2][j+2] = dead_space_three if v_map[i+2][j+2] < dead_space_three else v_map[i+2][j+2]
                                    v_map[i+3][j+3] = dead_space_three if v_map[i+3][j+3] < dead_space_three else v_map[i+3][j+3]
                                    v_map[i+4][j+4] = dead_space_three if v_map[i+4][j+4] < dead_space_three else v_map[i+4][j+4]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i+n-1][j+n-1] = 0
                                else:
                                    v_map[i  ][j  ] = dead_three if v_map[i  ][j  ] < dead_three else v_map[i  ][j  ]
                                    v_map[i+1][j+1] = dead_three if v_map[i+1][j+1] < dead_three else v_map[i+1][j+1]
                                    v_map[i+2][j+2] = dead_three if v_map[i+2][j+2] < dead_three else v_map[i+2][j+2]
                                    v_map[i+3][j+3] = dead_three if v_map[i+3][j+3] < dead_three else v_map[i+3][j+3]
                                    v_map[i+4][j+4] = dead_three if v_map[i+4][j+4] < dead_three else v_map[i+4][j+4]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i+n-1][j+n-1] = 0
                                    
                        elif seven_block[first_self] == 0 and seven_block[first_self+5] == 0:
                            v_map[i+first_self  ][j+first_self  ] = space_three if v_map[i+first_self  ][j+first_self  ] < space_three else v_map[i+first_self  ][j+first_self  ]
                            v_map[i+first_self+1][j+first_self+1] = space_three if v_map[i+first_self+1][j+first_self+1] < space_three else v_map[i+first_self+1][j+first_self+1]
                            v_map[i+first_self+2][j+first_self+2] = space_three if v_map[i+first_self+2][j+first_self+2] < space_three else v_map[i+first_self+2][j+first_self+2]
                            v_map[i+first_self+3][j+first_self+3] = space_three if v_map[i+first_self+3][j+first_self+3] < space_three else v_map[i+first_self+3][j+first_self+3]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j+n-1] = 0
                                    
                        elif seven_block[first_self] == 0 and seven_block[first_self+3] == 0:
                            v_map[i+first_self  ][j+first_self  ] = dead_space_three if v_map[i+first_self  ][j+first_self  ] < dead_space_three else v_map[i+first_self  ][j+first_self  ]
                            v_map[i+first_self+1][j+first_self+1] = dead_space_three if v_map[i+first_self+1][j+first_self+1] < dead_space_three else v_map[i+first_self+1][j+first_self+1]
                            v_map[i+first_self+2][j+first_self+2] = dead_space_three if v_map[i+first_self+2][j+first_self+2] < dead_space_three else v_map[i+first_self+2][j+first_self+2]
                            v_map[i+first_self+3][j+first_self+3] = dead_space_three if v_map[i+first_self+3][j+first_self+3] < dead_space_three else v_map[i+first_self+3][j+first_self+3]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j+n-1] = 0
                                    
                        elif seven_block[first_self+5] == 0 and seven_block[first_self+2] == 0:
                            v_map[i+first_self  ][j+first_self  ] = dead_space_three if v_map[i+first_self  ][j+first_self  ] < dead_space_three else v_map[i+first_self  ][j+first_self  ]
                            v_map[i+first_self+1][j+first_self+1] = dead_space_three if v_map[i+first_self+1][j+first_self+1] < dead_space_three else v_map[i+first_self+1][j+first_self+1]
                            v_map[i+first_self+2][j+first_self+2] = dead_space_three if v_map[i+first_self+2][j+first_self+2] < dead_space_three else v_map[i+first_self+2][j+first_self+2]
                            v_map[i+first_self+3][j+first_self+3] = dead_space_three if v_map[i+first_self+3][j+first_self+3] < dead_space_three else v_map[i+first_self+3][j+first_self+3]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j+n-1] = 0
                        
                        else:
                            v_map[i+first_self  ][j+first_self  ] = dead_three if v_map[i+first_self  ][j+first_self  ] < dead_three else v_map[i+first_self  ][j+first_self  ]
                            v_map[i+first_self+1][j+first_self+1] = dead_three if v_map[i+first_self+1][j+first_self+1] < dead_three else v_map[i+first_self+1][j+first_self+1]
                            v_map[i+first_self+2][j+first_self+2] = dead_three if v_map[i+first_self+2][j+first_self+2] < dead_three else v_map[i+first_self+2][j+first_self+2]
                            v_map[i+first_self+3][j+first_self+3] = dead_three if v_map[i+first_self+3][j+first_self+3] < dead_three else v_map[i+first_self+3][j+first_self+3]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j+n-1] = 0
                                    
                    elif consecutive_count_max == 1:
                        if seven_block[0] == 0 or seven_block[6] == 0:
                            v_map[i  ][j  ] = dead_space_three if v_map[i  ][j  ] < dead_space_three else v_map[i  ][j  ]
                            v_map[i+1][j+1] = dead_space_three if v_map[i+1][j+1] < dead_space_three else v_map[i+1][j+1]
                            v_map[i+2][j+2] = dead_space_three if v_map[i+2][j+2] < dead_space_three else v_map[i+2][j+2]
                            v_map[i+3][j+3] = dead_space_three if v_map[i+3][j+3] < dead_space_three else v_map[i+3][j+3]
                            v_map[i+4][j+4] = dead_space_three if v_map[i+4][j+4] < dead_space_three else v_map[i+4][j+4]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j+n-1] = 0
                        else:
                            v_map[i  ][j  ] = dead_three if v_map[i  ][j  ] < dead_three else v_map[i  ][j  ]
                            v_map[i+1][j+1] = dead_three if v_map[i+1][j+1] < dead_three else v_map[i+1][j+1]
                            v_map[i+2][j+2] = dead_three if v_map[i+2][j+2] < dead_three else v_map[i+2][j+2]
                            v_map[i+3][j+3] = dead_three if v_map[i+3][j+3] < dead_three else v_map[i+3][j+3]
                            v_map[i+4][j+4] = dead_three if v_map[i+4][j+4] < dead_three else v_map[i+4][j+4]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j+n-1] = 0
                            
                elif self_count == 2:
                    if consecutive_count_max == 2:
                        if seven_block[first_self] == 0 and seven_block[first_self+3] == 0:
                            v_map[i+first_self  ][j+first_self  ] = free_two if v_map[i+first_self  ][j+first_self  ] < free_two else v_map[i+first_self  ][j+first_self  ]
                            v_map[i+first_self+1][j+first_self+1] = free_two if v_map[i+first_self+1][j+first_self+1] < free_two else v_map[i+first_self+1][j+first_self+1]
                        else:
                            v_map[i+first_self  ][j+first_self  ] = dead_two if v_map[i+first_self  ][j+first_self  ] < dead_two else v_map[i+first_self  ][j+first_self  ]
                            v_map[i+first_self+1][j+first_self+1] = dead_two if v_map[i+first_self+1][j+first_self+1] < dead_two else v_map[i+first_self+1][j+first_self+1]
                            
                    else:
                        if seven_block[first_self] == 0 and seven_block[first_self+4] == 0:
                            v_map[i+first_self  ][j+first_self  ] = space_two if v_map[i+first_self  ][j+first_self  ] < space_two else v_map[i+first_self  ][j+first_self  ]
                            v_map[i+first_self+1][j+first_self+1] = space_two if v_map[i+first_self+1][j+first_self+1] < space_two else v_map[i+first_self+1][j+first_self+1]
                            v_map[i+first_self+2][j+first_self+2] = space_two if v_map[i+first_self+2][j+first_self+2] < space_two else v_map[i+first_self+2][j+first_self+2]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j+n-1] = 0
                        else:
                            v_map[i+first_self  ][j+first_self  ] = dead_two if v_map[i+first_self  ][j+first_self  ] < dead_two else v_map[i+first_self  ][j+first_self  ]
                            v_map[i+first_self+1][j+first_self+1] = dead_two if v_map[i+first_self+1][j+first_self+1] < dead_two else v_map[i+first_self+1][j+first_self+1]
                            v_map[i+first_self+2][j+first_self+2] = dead_two if v_map[i+first_self+2][j+first_self+2] < dead_two else v_map[i+first_self+2][j+first_self+2]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i+n-1][j+n-1] = 0

In [121]:
#test right down
v_map = np.zeros([7,7])
board = np.zeros([7,7])
board[0][0] = 0
board[1][1] = 2
board[2][2] = 1
board[3][3] = 1
board[4][4] = 2
board[5][5] = 0
board[6][6] = 0

find_winning_block_rd(board, 1, v_map)

print_board(board)
print(v_map)


#check right donw
  0   1   2   3   4   5   6 
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 0
 --- --- --- --- --- --- ---
|   | # |   |   |   |   |   | 1
 --- --- --- --- --- --- ---
|   |   | @ |   |   |   |   | 2
 --- --- --- --- --- --- ---
|   |   |   | @ |   |   |   | 3
 --- --- --- --- --- --- ---
|   |   |   |   | # |   |   | 4
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 5
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 6
 --- --- --- --- --- --- ---
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [124]:

def find_winning_block_ru(board, player, v_map):
    print('#check right up')
    for i in range(6,3,-1):
        for j in range(3):
            count = 0
            self_count = 0
            consecutive_count = 0
            consecutive_count_max = 0
            first_self = -1
            seven_block = np.zeros(7)
            for k in range(5):
                if board[i-k][j+k] == player:
                    consecutive_count += 1
                    v_map[i-k][j+k] = single if v_map[i-k][j+k] < single else v_map[i-k][j+k]
                    count+=1
                    self_count+=1
                    seven_block[k+1] = 1
#                     print('fs', first_self, 'k', k)
                    if first_self == -1:
                        first_self = k
#                     print('fs', first_self, 'k', k)
                    
                elif board[i-k][j+k] == 0:
                    consecutive_count_max = consecutive_count if consecutive_count > consecutive_count_max else consecutive_count_max
                    consecutive_count = 0
                    count+=1
                    
            consecutive_count_max = consecutive_count if consecutive_count > consecutive_count_max else consecutive_count_max
            
            if i+1 <= 6 and j-1>=0:
                if board[i+1][j-1] != 0 and board[i+1][j-1] != player:
                    seven_block[0] = -1
            else:
                seven_block[0] = -1
            
            if i-5 <= 0 and j+5<=6:
                if board[i-5][j+5] != 0 and board[i-5][j+5] != player:
                    seven_block[6] = -1
            else:
                seven_block[6] = -1
                    
#             print(seven_block)
            if count == 5:
                if self_count == 5:
                    v_map[i  ][j  ] = np.inf
                    v_map[i-1][j+1] = np.inf
                    v_map[i-2][j+2] = np.inf
                    v_map[i-3][j+3] = np.inf
                    v_map[i-4][j+4] = np.inf
                elif self_count == 4:
                    if consecutive_count_max == 4:
                        if seven_block[first_self] == 0 and seven_block[first_self+5] == 0:
                            v_map[i-first_self  ][j+first_self  ] = free_four if v_map[i-first_self  ][j+first_self  ] < free_four else v_map[i-first_self  ][j+first_self  ]
                            v_map[i-first_self-1][j+first_self+1] = free_four if v_map[i-first_self-1][j+first_self+1] < free_four else v_map[i-first_self-1][j+first_self+1]
                            v_map[i-first_self-2][j+first_self+2] = free_four if v_map[i-first_self-2][j+first_self+2] < free_four else v_map[i-first_self-2][j+first_self+2]
                            v_map[i-first_self-3][j+first_self+3] = free_four if v_map[i-first_self-3][j+first_self+3] < free_four else v_map[i-first_self-3][j+first_self+3]
                        else:
                            v_map[i-first_self  ][j+first_self  ] = dead_four if v_map[i-first_self  ][j+first_self  ] < dead_four else v_map[i-first_self  ][j+first_self  ]
                            v_map[i-first_self-1][j+first_self+1] = dead_four if v_map[i-first_self-1][j+first_self+1] < dead_four else v_map[i-first_self-1][j+first_self+1]
                            v_map[i-first_self-2][j+first_self+2] = dead_four if v_map[i-first_self-2][j+first_self+2] < dead_four else v_map[i-first_self-2][j+first_self+2]
                            v_map[i-first_self-3][j+first_self+3] = dead_four if v_map[i-first_self-3][j+first_self+3] < dead_four else v_map[i-first_self-3][j+first_self+3]
                    
                    elif consecutive_count_max == 3:
                        if seven_block[2] == 0:
                            if seven_block[6] == 0:
                                v_map[i  ][j  ] = space_four if v_map[i  ][j  ] < space_four else v_map[i  ][j  ]
                                v_map[i-1][j+1] = space_four if v_map[i-1][j+1] < space_four else v_map[i-1][j+1]
                                v_map[i-2][j+2] = space_four if v_map[i-2][j+2] < space_four else v_map[i-2][j+2]
                                v_map[i-3][j+3] = space_four if v_map[i-3][j+3] < space_four else v_map[i-3][j+3]
                                v_map[i-4][j+4] = space_four if v_map[i-4][j+4] < space_four else v_map[i-4][j+4]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i-n+1][j+n-1] = 0
                            else:
                                v_map[i  ][j  ] = dead_four if v_map[i  ][j  ] < dead_four else v_map[i  ][j  ]
                                v_map[i-1][j+1] = dead_four if v_map[i-1][j+1] < dead_four else v_map[i-1][j+1]
                                v_map[i-2][j+2] = dead_four if v_map[i-2][j+2] < dead_four else v_map[i-2][j+2]
                                v_map[i-3][j+3] = dead_four if v_map[i-3][j+3] < dead_four else v_map[i-3][j+3]
                                v_map[i-4][j+4] = dead_four if v_map[i-4][j+4] < dead_four else v_map[i-4][j+4]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i-n+1][j+n-1] = 0
                        elif seven_block[4] == 0:
                            if seven_block[0] == 0:
                                v_map[i  ][j  ] = space_four if v_map[i  ][j  ] < space_four else v_map[i  ][j  ]
                                v_map[i-1][j+1] = space_four if v_map[i-1][j+1] < space_four else v_map[i-1][j+1]
                                v_map[i-2][j+2] = space_four if v_map[i-2][j+2] < space_four else v_map[i-2][j+2]
                                v_map[i-3][j+3] = space_four if v_map[i-3][j+3] < space_four else v_map[i-3][j+3]
                                v_map[i-4][j+4] = space_four if v_map[i-4][j+4] < space_four else v_map[i-4][j+4]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i-n+1][j+n-1] = 0
                            else:
                                v_map[i  ][j  ] = dead_four if v_map[i  ][j  ] < dead_four else v_map[i  ][j  ]
                                v_map[i-1][j+1] = dead_four if v_map[i-1][j+1] < dead_four else v_map[i-1][j+1]
                                v_map[i-2][j+2] = dead_four if v_map[i-2][j+2] < dead_four else v_map[i-2][j+2]
                                v_map[i-3][j+3] = dead_four if v_map[i-3][j+3] < dead_four else v_map[i-3][j+3]
                                v_map[i-4][j+4] = dead_four if v_map[i-4][j+4] < dead_four else v_map[i-4][j+4]
                                for n in range(1,6):
                                    if seven_block[n] == 0:
                                        v_map[i-n+1][j+n-1] = 0
                    else:
                        v_map[i  ][j  ] = dead_four if v_map[i  ][j  ] < dead_four else v_map[i  ][j  ]
                        v_map[i-1][j+1] = dead_four if v_map[i-1][j+1] < dead_four else v_map[i-1][j+1]
                        v_map[i-2][j+2] = dead_four if v_map[i-2][j+2] < dead_four else v_map[i-2][j+2]
                        v_map[i-3][j+3] = dead_four if v_map[i-3][j+3] < dead_four else v_map[i-3][j+3]
                        v_map[i-4][j+4] = dead_four if v_map[i-4][j+4] < dead_four else v_map[i-4][j+4]
                        for n in range(1,6):
                            if seven_block[n] == 0:
                                v_map[i-n+1][j+n-1] = 0
                                
                elif self_count == 3:
                    if consecutive_count_max == 3:
                        if seven_block[first_self] == 0 and seven_block[first_self+4] == 0:
                            v_map[i-first_self  ][j+first_self  ] = free_three if v_map[i-first_self  ][j+first_self  ] < free_three else v_map[i-first_self  ][j+first_self  ]
                            v_map[i-first_self-1][j+first_self+1] = free_three if v_map[i-first_self-1][j+first_self+1] < free_three else v_map[i-first_self-1][j+first_self+1]
                            v_map[i-first_self-2][j+first_self+2] = free_three if v_map[i-first_self-2][j+first_self+2] < free_three else v_map[i-first_self-2][j+first_self+2]
#                             v_map[i+first_self+3][j+first_self+3] = free_three if v_map[i+first_self+3][j+first_self+3] < free_three else v_map[i+first_self+3][j+first_self+3]
                        else:
                            v_map[i-first_self  ][j+first_self  ] = dead_three if v_map[i-first_self  ][j+first_self  ] < dead_three else v_map[i-first_self  ][j+first_self  ]
                            v_map[i-first_self-1][j+first_self+1] = dead_three if v_map[i-first_self-1][j+first_self+1] < dead_three else v_map[i-first_self-1][j+first_self+1]
                            v_map[i-first_self-2][j+first_self+2] = dead_three if v_map[i-first_self-2][j+first_self+2] < dead_three else v_map[i-first_self-2][j+first_self+2]
#                             v_map[i+first_self+3][j+first_self+3] = free_three if v_map[i+first_self+3][j+first_self+3] < free_three else v_map[i+first_self+3][j+first_self+3]
                            
                    elif consecutive_count_max == 2:
                        if seven_block[1] == 1 and seven_block[5] == 1:
                            if seven_block[2] == 0 and seven_block[3] == 0:
                                if seven_block[6] == 0:
                                    v_map[i  ][j  ] = dead_space_three if v_map[i  ][j  ] < dead_space_three else v_map[i  ][j  ]
                                    v_map[i-1][j+1] = dead_space_three if v_map[i-1][j+1] < dead_space_three else v_map[i-1][j+1]
                                    v_map[i-2][j+2] = dead_space_three if v_map[i-2][j+2] < dead_space_three else v_map[i-2][j+2]
                                    v_map[i-3][j+3] = dead_space_three if v_map[i-3][j+3] < dead_space_three else v_map[i-3][j+3]
                                    v_map[i-4][j+4] = dead_space_three if v_map[i-4][j+4] < dead_space_three else v_map[i-4][j+4]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i-n+1][j+n-1] = 0
                                else:
                                    v_map[i  ][j  ] = dead_three if v_map[i  ][j  ] < dead_three else v_map[i  ][j  ]
                                    v_map[i-1][j+1] = dead_three if v_map[i-1][j+1] < dead_three else v_map[i-1][j+1]
                                    v_map[i-2][j+2] = dead_three if v_map[i-2][j+2] < dead_three else v_map[i-2][j+2]
                                    v_map[i-3][j+3] = dead_three if v_map[i-3][j+3] < dead_three else v_map[i-3][j+3]
                                    v_map[i-4][j+4] = dead_three if v_map[i-4][j+4] < dead_three else v_map[i-4][j+4]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i-n+1][j+n-1] = 0
                            if seven_block[3] == 0 and seven_block[4] == 0:
                                if seven_block[0] == 0:
                                    v_map[i  ][j  ] = dead_space_three if v_map[i  ][j  ] < dead_space_three else v_map[i  ][j  ]
                                    v_map[i-1][j+1] = dead_space_three if v_map[i-1][j+1] < dead_space_three else v_map[i-1][j+1]
                                    v_map[i-2][j+2] = dead_space_three if v_map[i-2][j+2] < dead_space_three else v_map[i-2][j+2]
                                    v_map[i-3][j+3] = dead_space_three if v_map[i-3][j+3] < dead_space_three else v_map[i-3][j+3]
                                    v_map[i-4][j+4] = dead_space_three if v_map[i-4][j+4] < dead_space_three else v_map[i-4][j+4]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i-n+1][j+n-1] = 0
                                else:
                                    v_map[i  ][j  ] = dead_three if v_map[i  ][j  ] < dead_three else v_map[i  ][j  ]
                                    v_map[i-1][j+1] = dead_three if v_map[i-1][j+1] < dead_three else v_map[i-1][j+1]
                                    v_map[i-2][j+2] = dead_three if v_map[i-2][j+2] < dead_three else v_map[i-2][j+2]
                                    v_map[i-3][j+3] = dead_three if v_map[i-3][j+3] < dead_three else v_map[i-3][j+3]
                                    v_map[i-4][j+4] = dead_three if v_map[i-4][j+4] < dead_three else v_map[i-4][j+4]
                                    for n in range(1,6):
                                        if seven_block[n] == 0:
                                            v_map[i-n+1][j+n-1] = 0
                                    
                        elif seven_block[first_self] == 0 and seven_block[first_self+5] == 0:
                            v_map[i-first_self  ][j+first_self  ] = space_three if v_map[i-first_self  ][j+first_self  ] < space_three else v_map[i-first_self  ][j+first_self  ]
                            v_map[i-first_self-1][j+first_self+1] = space_three if v_map[i-first_self-1][j+first_self+1] < space_three else v_map[i-first_self-1][j+first_self+1]
                            v_map[i-first_self-2][j+first_self+2] = space_three if v_map[i-first_self-2][j+first_self+2] < space_three else v_map[i-first_self-2][j+first_self+2]
                            v_map[i-first_self-3][j+first_self+3] = space_three if v_map[i-first_self-3][j+first_self+3] < space_three else v_map[i-first_self-3][j+first_self+3]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i-n+1][j+n-1] = 0
                                    
                        elif seven_block[first_self] == 0 and seven_block[first_self+3] == 0:
                            v_map[i-first_self  ][j+first_self  ] = dead_space_three if v_map[i-first_self  ][j+first_self  ] < dead_space_three else v_map[i-first_self  ][j+first_self  ]
                            v_map[i-first_self-1][j+first_self+1] = dead_space_three if v_map[i-first_self-1][j+first_self+1] < dead_space_three else v_map[i-first_self+1][j+first_self+1]
                            v_map[i-first_self-2][j+first_self+2] = dead_space_three if v_map[i-first_self-2][j+first_self+2] < dead_space_three else v_map[i-first_self+2][j+first_self+2]
                            v_map[i-first_self-3][j+first_self+3] = dead_space_three if v_map[i-first_self-3][j+first_self+3] < dead_space_three else v_map[i-first_self+3][j+first_self+3]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i-n+1][j+n-1] = 0
                                    
                        elif seven_block[first_self+5] == 0 and seven_block[first_self+2] == 0:
                            v_map[i-first_self  ][j+first_self  ] = dead_space_three if v_map[i-first_self  ][j+first_self  ] < dead_space_three else v_map[i-first_self  ][j+first_self  ]
                            v_map[i-first_self-1][j+first_self+1] = dead_space_three if v_map[i-first_self-1][j+first_self+1] < dead_space_three else v_map[i-first_self-1][j+first_self+1]
                            v_map[i-first_self-2][j+first_self+2] = dead_space_three if v_map[i-first_self-2][j+first_self+2] < dead_space_three else v_map[i-first_self-2][j+first_self+2]
                            v_map[i-first_self-3][j+first_self+3] = dead_space_three if v_map[i-first_self-3][j+first_self+3] < dead_space_three else v_map[i-first_self-3][j+first_self+3]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i-n+1][j+n-1] = 0
                        
                        else:
                            v_map[i-first_self  ][j+first_self  ] = dead_three if v_map[i-first_self  ][j+first_self  ] < dead_three else v_map[i-first_self  ][j+first_self  ]
                            v_map[i-first_self-1][j+first_self+1] = dead_three if v_map[i-first_self-1][j+first_self+1] < dead_three else v_map[i-first_self-1][j+first_self+1]
                            v_map[i-first_self-2][j+first_self+2] = dead_three if v_map[i-first_self-2][j+first_self+2] < dead_three else v_map[i-first_self-2][j+first_self+2]
                            v_map[i-first_self-3][j+first_self+3] = dead_three if v_map[i-first_self-3][j+first_self+3] < dead_three else v_map[i-first_self-3][j+first_self+3]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i-n+1][j+n-1] = 0
                                    
                    elif consecutive_count_max == 1:
                        if seven_block[0] == 0 or seven_block[6] == 0:
                            v_map[i  ][j  ] = dead_space_three if v_map[i  ][j  ] < dead_space_three else v_map[i  ][j  ]
                            v_map[i-1][j+1] = dead_space_three if v_map[i-1][j+1] < dead_space_three else v_map[i-1][j+1]
                            v_map[i-2][j+2] = dead_space_three if v_map[i-2][j+2] < dead_space_three else v_map[i-2][j+2]
                            v_map[i-3][j+3] = dead_space_three if v_map[i-3][j+3] < dead_space_three else v_map[i-3][j+3]
                            v_map[i-4][j+4] = dead_space_three if v_map[i-4][j+4] < dead_space_three else v_map[i-4][j+4]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i-n+1][j+n-1] = 0
                        else:
                            v_map[i  ][j  ] = dead_three if v_map[i  ][j  ] < dead_three else v_map[i  ][j  ]
                            v_map[i-1][j+1] = dead_three if v_map[i-1][j+1] < dead_three else v_map[i-1][j+1]
                            v_map[i-2][j+2] = dead_three if v_map[i-2][j+2] < dead_three else v_map[i-2][j+2]
                            v_map[i-3][j+3] = dead_three if v_map[i-3][j+3] < dead_three else v_map[i-3][j+3]
                            v_map[i-4][j+4] = dead_three if v_map[i-4][j+4] < dead_three else v_map[i-4][j+4]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i-n+1][j+n-1] = 0
                            
                elif self_count == 2:
                    if consecutive_count_max == 2:
                        if seven_block[first_self] == 0 and seven_block[first_self+3] == 0:
                            v_map[i-first_self  ][j+first_self  ] = free_two if v_map[i-first_self  ][j+first_self  ] < free_two else v_map[i-first_self  ][j+first_self  ]
                            v_map[i-first_self-1][j+first_self+1] = free_two if v_map[i-first_self-1][j+first_self-1] < free_two else v_map[i-first_self-1][j+first_self+1]
                        else:
                            v_map[i-first_self  ][j+first_self  ] = dead_two if v_map[i-first_self  ][j+first_self  ] < dead_two else v_map[i-first_self  ][j+first_self  ]
                            v_map[i-first_self-1][j+first_self+1] = dead_two if v_map[i-first_self-1][j+first_self-1] < dead_two else v_map[i-first_self-1][j+first_self+1]
                            
                    else:
                        if (seven_block[1] !+ 0 and seven
                        
                        
                        
                        
                        if seven_block[first_self] == 0 and seven_block[first_self+4] == 0:
                            v_map[i-first_self  ][j+first_self  ] = space_two if v_map[i-first_self  ][j+first_self  ] < space_two else v_map[i-first_self  ][j+first_self  ]
                            v_map[i-first_self-1][j+first_self+1] = space_two if v_map[i-first_self-1][j+first_self+1] < space_two else v_map[i-first_self-1][j+first_self+1]
                            v_map[i-first_self-2][j+first_self+2] = space_two if v_map[i-first_self-2][j+first_self+2] < space_two else v_map[i-first_self-2][j+first_self+2]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i-n+1][j+n-1] = 0
                        else:
                            v_map[i-first_self  ][j+first_self  ] = dead_two if v_map[i-first_self  ][j+first_self  ] < dead_two else v_map[i-first_self  ][j+first_self  ]
                            v_map[i-first_self-1][j+first_self+1] = dead_two if v_map[i-first_self-1][j+first_self+1] < dead_two else v_map[i-first_self-1][j+first_self+1]
                            v_map[i-first_self-2][j+first_self+2] = dead_two if v_map[i-first_self-2][j+first_self+2] < dead_two else v_map[i-first_self-2][j+first_self+2]
                            for n in range(1,6):
                                if seven_block[n] == 0:
                                    v_map[i-n+1][j+n-1] = 0

In [162]:
#test right up
v_map = np.zeros([7,7])
board = np.zeros([7,7])
board[0][6] = 2
board[1][5] = 1
board[2][4] = 1
board[3][3] = 0
board[4][2] = 1
board[5][1] = 0
board[6][0] = 0

find_winning_block_ru(board, 1, v_map)

print_board(board)
print(v_map)


#check right up
  0   1   2   3   4   5   6 
 --- --- --- --- --- --- ---
|   |   |   |   |   |   | # | 0
 --- --- --- --- --- --- ---
|   |   |   |   |   | @ |   | 1
 --- --- --- --- --- --- ---
|   |   |   |   | @ |   |   | 2
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 3
 --- --- --- --- --- --- ---
|   |   | @ |   |   |   |   | 4
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 5
 --- --- --- --- --- --- ---
|   |   |   |   |   |   |   | 6
 --- --- --- --- --- --- ---
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  5.  0.]
 [ 0.  0.  0.  0.  5.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  5.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [149]:
def evaluation_heuristic(b, max_agent):
    v_map_horiz_1 = np.zeros([7,7])
    v_map_verical_1 = np.zeros([7,7])
    v_map_rd_1 = np.zeros([7,7])
    v_map_ru_1 = np.zeros([7,7])
    
    v_map_horiz_1 = np.zeros([7,7])
    v_map_vertical_1 = np.zeros([7,7])
    v_map_ru_1 = np.zeros([7,7])
    v_map_rd_1 = np.zeros([7,7])
    
    find_winning_block_horiz(board, max_agent, v_map_horiz_1)
    find_winning_block_vertical(board, max_agent, v_map_vertical_1)
    find_winning_block_ru(board, max_agent, v_map_ru_1)
    find_winning_block_rd(board, max_agent, v_map_rd_1)
    
    for i in range(7):
        for j in range(7):
            v_map_horiz_1[i][j] = v_map_horiz_1[i][j]*v_map_vertical_1[i][j]*v_map_ru_1[i][j]*v_map_rd_1[i][j]
            
    n = max_agent%2 + 1
            
    
    find_winning_block_horiz(board, n, v_map_horiz_2)
    find_winning_block_vertical(board, n, v_map_vertical_2)
    find_winning_block_ru(board, n, v_map_ru_2)
    find_winning_block_rd(board, n, v_map_rd_2)
    
    for i in range(7):
        for j in range(7):
            v_map_horiz_2[i][j] = v_map_horiz_2[i][j]*v_map_vertical_2[i][j]*v_map_ru_2[i][j]*v_map_rd_2[i][j]
            
    for i in range(7):
        for j in range(7):
            v_map_horiz_1[i][j] = v_map_horiz_1[i][j] -v_map_horiz_2[i][j]
            
    return np.sum(v_map_horiz_1)
            
    
    
    
    

In [147]:
print(np.inf*8)

inf
